### ISSUE TITLE
models directory

### ISSUE THREAD

**Issue by retteghy** [curvedinf/dir-assistant#1]
> Download your favorite LLM gguf and place it in the models directory. You will also need to download an embedding model gguf and place it in the same directory.

I recommend that instead of asking users to place those files inside models you allow users to point to the directory where they store those gguf files (they are likely not only using those files to be used with dir-assistant, but other programs as well)

**Comment by bringfido-adams** [comment]
I'd like to hear more opinions on this, as this is the current standard way runners organize models.

For now you can specify a relative path from the models dir ("../other-project/models/model.gguf") or use a symlink as a workaround.

**Comment by curvedinf** [comment]
I'd like to hear more opinions on this, as the models directory is currently a standard used by other model runners.

For now you can use relative pathing ("../other-project/models/model.gguf") or symlinks as a workaround.

**Comment by sammcj** [comment]
I think the users should be prompted for a path to use for models with a sensible default, e.g. `MODELS_DIR=${MODELS_DIR:-$HOME/.cache/dir-assistant/models}`

**Comment by curvedinf** [comment]
Closing this as I added support for changing the models directory via the new `MODELS_PATH` option.
