### ISSUE TITLE
Issue with dir-assistant installation on PipX

### ISSUE THREAD

**Issue by strawberrymelonpanda** [curvedinf/dir-assistant#7]
I've encountered an issue when installing dir-assistant using PipX. 

**Error Details:**
The platform setup script is failing because it expects to use the current pip, but PipX separates packages from the system's python and pip.

https://github.com/curvedinf/dir-assistant/blob/0e275d4096b36cb35d7a9a496a61b5ae4f0c935f/dir_assistant/platform_setup.py#L27

**Workaround:**

`pipx runpip dir-assistant` instead of `pip` after installing dir-assistant using PipX:
```bash
CMAKE_ARGS=-DGGML_CUDA=on pipx runpip dir-assistant install --upgrade --force-reinstall --no-cache-dir llama-cpp-python faiss-cpu
```
I've tested this workaround and it works for me. Hope this helps.

**Comment by curvedinf** [comment]
When you reported this I didn't know pipx was the new default global python environment process for Ubuntu 24.04. I learned that it is, so I've implemented some features and documentation to support it.
